version: "3.8"

services:
  frontend:
    build: ./example-frontend
    ports:
    - "5000:5000"
  backend:
    build: ./example-backend
    ports:
    - "8080:8080"
    environment:
      REQUEST_ORIGIN: http://localhost
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postgres
  redis:
    image: redis
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/db_files
    container_name: db_postgres
    volumes:
     - ./database:/var/lib/postgresql/data/db_files
  web:
    image: nginx:1.21-alpine
    volumes:
    - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
